[makefiles] Run tests in Rust Makefile
Signed-off-by: Christopher Hall <hsw@ms2.hinet.net>

diff --git a/makefiles/rust/BSDmakefile b/makefiles/rust/BSDmakefile
--- a/makefiles/rust/BSDmakefile
+++ b/makefiles/rust/BSDmakefile
@@ -96,6 +96,29 @@ emacs-9:
 	 fi
 
 
+# -1  => run all tests
+.PHONY: test-1
+test-1:
+	@printf '\n===> \033[1;34;47m%s\033[0m\n' 'run all tests'
+	@cd '${THIS_DIR}' ; \
+	 program_root='' ; \
+	 while : ; \
+	 do \
+	   [ X"$$(realpath '.')" = X"${PROJECTS}" ] && break ; \
+	   [ -f "Cargo.toml" ] && program_root="$${PWD}" && break ; \
+	   cd .. ; \
+	 done ; \
+	 if [ -n "$${program_root}" ] ; \
+	 then \
+	   cd "$${program_root}" ; \
+	   printf '\n===> compilation-dir: %s\n\n' "$${PWD}" ; \
+	   cargo test -v ; \
+	 else \
+	   printf '\n===> program not found\n' ; \
+	   exit 1 ; \
+	 fi
+
+
 # 999 => help
 .PHONY: emacs-999
 emacs-999: help
