[Emakefiles] Rust test with backtrace
Signed-off-by: Christopher Hall <hsw@ms2.hinet.net>

diff --git a/Emakefiles/rust/Emakefile b/Emakefiles/rust/Emakefile
--- a/Emakefiles/rust/Emakefile
+++ b/Emakefiles/rust/Emakefile
@@ -136,6 +136,30 @@ test-1:
 	 fi
 
 
+# -2 => test Rust program (back trace)
+.PHONY: test-2
+test-2:
+	@printf '\n===> \033[1;34;47m%s\033[0m\n' 'test Rust program'
+	@cd '${THIS_DIR}' ; \
+	 program_root='' ; \
+	 while : ; \
+	 do \
+	   [ X"$$(realpath '.')" = X"${PROJECTS_DIR}" ] && break ; \
+	   [ -f "Cargo.toml" ] && program_root="$${PWD}" && break ; \
+	   cd .. ; \
+	 done ; \
+	 if [ -n "$${program_root}" ] ; \
+	 then \
+	   cd "$${program_root}" ; \
+	   printf '\n===> compilation-dir: %s\n\n' "$${PWD}" ; \
+	   export RUST_BACKTRACE=full ; \
+	   cargo test ; \
+	 else \
+	   printf '\n===> program not found\n' ; \
+	   exit 1 ; \
+	 fi
+
+
 # 999 => help
 .PHONY: emacs-999
 emacs-999: help
