[Emakefiles] compile/install rust addition
Signed-off-by: Christopher Hall <hsw@ms2.hinet.net>

diff --git a/Emakefiles/rust/Emakefile b/Emakefiles/rust/Emakefile
--- a/Emakefiles/rust/Emakefile
+++ b/Emakefiles/rust/Emakefile
@@ -73,6 +73,28 @@ emacs-1:
 	 fi
 
 
+# 2 => compile/install Rust program
+.PHONY: emacs-2
+emacs-2:
+	@printf '\n===> \033[1;34;47m%s\033[0m\n' 'compile/install Rust program'
+	@cd '${THIS_DIR}' ; \
+	 program_root='' ; \
+	 while : ; \
+	 do \
+	   [ X"$$(realpath '.')" = X"${PROJECTS}" ] && break ; \
+	   [ -f "Cargo.toml" ] && program_root="$${PWD}" && break ; \
+	   cd .. ; \
+	 done ; \
+	 if [ -n "$${program_root}" ] ; \
+	 then \
+	   cd "$${program_root}" ; \
+	   printf '\n===> compilation-dir: %s\n\n' "$${PWD}" ; \
+	   cargo install --path=. --force ; \
+	 else \
+	   printf '\n===> program not found\n' ; \
+	   exit 1 ; \
+	 fi
+
 # 9 => clean cargo dependencies
 .PHONY: emacs-9
 emacs-9:
@@ -95,11 +117,10 @@ emacs-9:
 	   exit 1 ; \
 	 fi
 
-
-# -1  => run all tests
+# -1 => test Rust program
 .PHONY: test-1
 test-1:
-	@printf '\n===> \033[1;34;47m%s\033[0m\n' 'run all tests'
+	@printf '\n===> \033[1;34;47m%s\033[0m\n' 'test Rust program'
 	@cd '${THIS_DIR}' ; \
 	 program_root='' ; \
 	 while : ; \
@@ -112,7 +133,7 @@ test-1:
 	 then \
 	   cd "$${program_root}" ; \
 	   printf '\n===> compilation-dir: %s\n\n' "$${PWD}" ; \
-	   cargo test -v ; \
+	   cargo test ; \
 	 else \
 	   printf '\n===> program not found\n' ; \
 	   exit 1 ; \
